"""add metric tables

Revision ID: 11480bac1122
Revises: 5beaaa397ee2
Create Date: 2026-07-21 23:25:56.074998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11480bac1122'
down_revision: Union[str, Sequence[str], None] = '5beaaa397ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_types',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_metric_type_code', 'metric_types', ['code'], unique=False)
    op.create_table('scans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('SAFE', 'SUSPICIOUS', 'MALICIOUS', name='scan_verdict'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scans_user_id', 'scans', ['user_id'], unique=False)
    op.create_index('idx_scans_verdict', 'scans', ['verdict'], unique=False)
    op.create_table('scan_metrics',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('metric_type_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_metric_metric_type', 'scan_metrics', ['metric_type_id'], unique=False)
    op.create_index('idx_scan_metric_scan', 'scan_metrics', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scan_metric_scan', table_name='scan_metrics')
    op.drop_index('idx_scan_metric_metric_type', table_name='scan_metrics')
    op.drop_table('scan_metrics')
    op.drop_index('idx_scans_verdict', table_name='scans')
    op.drop_index('idx_scans_user_id', table_name='scans')
    op.drop_table('scans')
    op.drop_index('idx_metric_type_code', table_name='metric_types')
    op.drop_table('metric_types')
    # ### end Alembic commands ###
